# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: alexeykirinyuk/go_product_api/v1/go_product_api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import validate.validate_pb2
import google.api.annotations_pb2
import google.protobuf.timestamp_pb2
import alexeykirinyuk.go_product_api.v1.go_product_api_pb2


class GoProductApiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def DescribeProductV1(self, stream: 'grpclib.server.Stream[alexeykirinyuk.go_product_api.v1.go_product_api_pb2.DescribeProductV1Request, alexeykirinyuk.go_product_api.v1.go_product_api_pb2.DescribeProductV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def CreateProductV1(self, stream: 'grpclib.server.Stream[alexeykirinyuk.go_product_api.v1.go_product_api_pb2.CreateProductV1Request, alexeykirinyuk.go_product_api.v1.go_product_api_pb2.CreateProductV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def ListProductsV1(self, stream: 'grpclib.server.Stream[alexeykirinyuk.go_product_api.v1.go_product_api_pb2.ListProductsV1Request, alexeykirinyuk.go_product_api.v1.go_product_api_pb2.ListProductsV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def RemoveProductV1(self, stream: 'grpclib.server.Stream[alexeykirinyuk.go_product_api.v1.go_product_api_pb2.RemoveProductV1Request, alexeykirinyuk.go_product_api.v1.go_product_api_pb2.RemoveProductV1Response]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ozonmp.go_product_api.v1.GoProductApiService/DescribeProductV1': grpclib.const.Handler(
                self.DescribeProductV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                alexeykirinyuk.go_product_api.v1.go_product_api_pb2.DescribeProductV1Request,
                alexeykirinyuk.go_product_api.v1.go_product_api_pb2.DescribeProductV1Response,
            ),
            '/ozonmp.go_product_api.v1.GoProductApiService/CreateProductV1': grpclib.const.Handler(
                self.CreateProductV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                alexeykirinyuk.go_product_api.v1.go_product_api_pb2.CreateProductV1Request,
                alexeykirinyuk.go_product_api.v1.go_product_api_pb2.CreateProductV1Response,
            ),
            '/ozonmp.go_product_api.v1.GoProductApiService/ListProductsV1': grpclib.const.Handler(
                self.ListProductsV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                alexeykirinyuk.go_product_api.v1.go_product_api_pb2.ListProductsV1Request,
                alexeykirinyuk.go_product_api.v1.go_product_api_pb2.ListProductsV1Response,
            ),
            '/ozonmp.go_product_api.v1.GoProductApiService/RemoveProductV1': grpclib.const.Handler(
                self.RemoveProductV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                alexeykirinyuk.go_product_api.v1.go_product_api_pb2.RemoveProductV1Request,
                alexeykirinyuk.go_product_api.v1.go_product_api_pb2.RemoveProductV1Response,
            ),
        }


class GoProductApiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DescribeProductV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.go_product_api.v1.GoProductApiService/DescribeProductV1',
            alexeykirinyuk.go_product_api.v1.go_product_api_pb2.DescribeProductV1Request,
            alexeykirinyuk.go_product_api.v1.go_product_api_pb2.DescribeProductV1Response,
        )
        self.CreateProductV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.go_product_api.v1.GoProductApiService/CreateProductV1',
            alexeykirinyuk.go_product_api.v1.go_product_api_pb2.CreateProductV1Request,
            alexeykirinyuk.go_product_api.v1.go_product_api_pb2.CreateProductV1Response,
        )
        self.ListProductsV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.go_product_api.v1.GoProductApiService/ListProductsV1',
            alexeykirinyuk.go_product_api.v1.go_product_api_pb2.ListProductsV1Request,
            alexeykirinyuk.go_product_api.v1.go_product_api_pb2.ListProductsV1Response,
        )
        self.RemoveProductV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.go_product_api.v1.GoProductApiService/RemoveProductV1',
            alexeykirinyuk.go_product_api.v1.go_product_api_pb2.RemoveProductV1Request,
            alexeykirinyuk.go_product_api.v1.go_product_api_pb2.RemoveProductV1Response,
        )
