// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: alexeykirinyuk/go_product_api/v1/go_product_api.proto

package go_product_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on CreateProductV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateProductV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 100 {
		return CreateProductV1RequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetCategory()); l < 1 || l > 100 {
		return CreateProductV1RequestValidationError{
			field:  "Category",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetDescription()); l < 1 || l > 1000 {
		return CreateProductV1RequestValidationError{
			field:  "Description",
			reason: "value length must be between 1 and 1000 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetBrand()); l < 1 || l > 50 {
		return CreateProductV1RequestValidationError{
			field:  "Brand",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
	}

	if m.GetCost() <= 0 {
		return CreateProductV1RequestValidationError{
			field:  "Cost",
			reason: "value must be greater than 0",
		}
	}

	if _, ok := _CreateProductV1Request_Currency_NotInLookup[m.GetCurrency()]; ok {
		return CreateProductV1RequestValidationError{
			field:  "Currency",
			reason: "value must not be in list [0]",
		}
	}

	return nil
}

// CreateProductV1RequestValidationError is the validation error returned by
// CreateProductV1Request.Validate if the designated constraints aren't met.
type CreateProductV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateProductV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateProductV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateProductV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateProductV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateProductV1RequestValidationError) ErrorName() string {
	return "CreateProductV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateProductV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateProductV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateProductV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateProductV1RequestValidationError{}

var _CreateProductV1Request_Currency_NotInLookup = map[Currency]struct{}{
	0: {},
}

// Validate checks the field values on CreateProductV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateProductV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetProduct()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateProductV1ResponseValidationError{
				field:  "Product",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreateProductV1ResponseValidationError is the validation error returned by
// CreateProductV1Response.Validate if the designated constraints aren't met.
type CreateProductV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateProductV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateProductV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateProductV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateProductV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateProductV1ResponseValidationError) ErrorName() string {
	return "CreateProductV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateProductV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateProductV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateProductV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateProductV1ResponseValidationError{}

// Validate checks the field values on DescribeProductV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeProductV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetProductId() <= 0 {
		return DescribeProductV1RequestValidationError{
			field:  "ProductId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// DescribeProductV1RequestValidationError is the validation error returned by
// DescribeProductV1Request.Validate if the designated constraints aren't met.
type DescribeProductV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeProductV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeProductV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeProductV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeProductV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeProductV1RequestValidationError) ErrorName() string {
	return "DescribeProductV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeProductV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeProductV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeProductV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeProductV1RequestValidationError{}

// Validate checks the field values on DescribeProductV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeProductV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetProduct()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribeProductV1ResponseValidationError{
				field:  "Product",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// DescribeProductV1ResponseValidationError is the validation error returned by
// DescribeProductV1Response.Validate if the designated constraints aren't met.
type DescribeProductV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeProductV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeProductV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeProductV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeProductV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeProductV1ResponseValidationError) ErrorName() string {
	return "DescribeProductV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeProductV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeProductV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeProductV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeProductV1ResponseValidationError{}

// Validate checks the field values on ListProductsV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListProductsV1Request) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// ListProductsV1RequestValidationError is the validation error returned by
// ListProductsV1Request.Validate if the designated constraints aren't met.
type ListProductsV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProductsV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProductsV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProductsV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProductsV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProductsV1RequestValidationError) ErrorName() string {
	return "ListProductsV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListProductsV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProductsV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProductsV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProductsV1RequestValidationError{}

// Validate checks the field values on ListProductsV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListProductsV1Response) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetProducts() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListProductsV1ResponseValidationError{
					field:  fmt.Sprintf("Products[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListProductsV1ResponseValidationError is the validation error returned by
// ListProductsV1Response.Validate if the designated constraints aren't met.
type ListProductsV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProductsV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProductsV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProductsV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProductsV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProductsV1ResponseValidationError) ErrorName() string {
	return "ListProductsV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListProductsV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProductsV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProductsV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProductsV1ResponseValidationError{}

// Validate checks the field values on RemoveProductV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemoveProductV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetProductId() <= 0 {
		return RemoveProductV1RequestValidationError{
			field:  "ProductId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// RemoveProductV1RequestValidationError is the validation error returned by
// RemoveProductV1Request.Validate if the designated constraints aren't met.
type RemoveProductV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveProductV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveProductV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveProductV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveProductV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveProductV1RequestValidationError) ErrorName() string {
	return "RemoveProductV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveProductV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveProductV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveProductV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveProductV1RequestValidationError{}

// Validate checks the field values on RemoveProductV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemoveProductV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetProduct()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RemoveProductV1ResponseValidationError{
				field:  "Product",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// RemoveProductV1ResponseValidationError is the validation error returned by
// RemoveProductV1Response.Validate if the designated constraints aren't met.
type RemoveProductV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveProductV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveProductV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveProductV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveProductV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveProductV1ResponseValidationError) ErrorName() string {
	return "RemoveProductV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveProductV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveProductV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveProductV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveProductV1ResponseValidationError{}

// Validate checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Product) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Category

	// no validation rules for Description

	// no validation rules for Brand

	// no validation rules for Cost

	// no validation rules for Currency

	if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProductValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ProductValidationError is the validation error returned by Product.Validate
// if the designated constraints aren't met.
type ProductValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductValidationError) ErrorName() string { return "ProductValidationError" }

// Error satisfies the builtin error interface
func (e ProductValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProduct.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductValidationError{}
